apiVersion: v1
kind: ConfigMap
metadata:
  name: execution-service-config
data:
  SERVICE_NAME: "execution-service"
  HTTP_PORT: "8080"
  MONGODB_READINESS_ENABLED: "false"
  RABBITMQ_URL: "amqp://rabbitmq.rabbitmq.svc.cluster.local:5672"
  RABBITMQ_CONSUMER_ENABLED: "false"
