apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: execution-service
      app.kubernetes.io/part-of: workshop-phase-4
    includeSelectors: true

images:
  - name: execution-service
    newName: execution-service
    newTag: latest
